name: rgb-tui
version: '1.0'
summary: A color picker in a terminal UI.
description: A color picker in a terminal UI.

grade: stable
confinement: strict
base: core18

apps:
  rgb-tui:
    command: rgb-tui

parts:
  rgb-tui:
    plugin: cmake
    source: https://github.com/ArthurSonzogni/rgb-tui
    source-type: git
    source-depth: 1
    build-snaps: [cmake/latest/edge] # We need cmake >= 3.11
    override-build: |
      /snap/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local \
        -DCMAKE_BUILD_TYPE=Release \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install

passthrough:
  title: rgb-tui
  license: MIT
